import { BadgeSchema } from '@schemas/badge'
import { LinkSchema } from '@schemas/links'
import { z } from 'astro/zod'

export const SidebarEntrySchema = z.object({
  /**
   * The order of this page in the navigation.
   * Pages are sorted by this value in ascending order. Then by slug.
   * If not provided, pages will be sorted alphabetically by slug.
   * If two pages have the same order value, they will be sorted alphabetically by slug.
   */
  order: z.number().optional(),

  /**
   * The label for this page in the navigation.
   * Defaults to the page `title` if not set.
   */
  label: z.string().optional(),

  /**
   * Prevents this page from being included in autogenerated sidebar groups.
   */
  hidden: z.boolean().default(false),

  /**
   * Adds a badge to the sidebar link.
   * Styles include "caution", "danger", "note", "subtle", "success".
   */
  badge: BadgeSchema.optional(),

  /**
   * Set the link for this page in the navigation.
   * link text will override the page title, and the label if provided.
   */
  link: LinkSchema.optional(),
})
